
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          distribution: graalvm-community
          java-version: 21
          cache: gradle
      - run: ./gradlew nativeTest
